name: Auto-build-project
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: zip the code
      run: |
        rm -r Auto-build
        mkdir Auto-build
        cp -r src Auto-build
        cd Auto-build
        zip -r maintenance-alerts.zip src
      
    - name: Release to Github
      run: echo "Release"
    
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "himashanasuraweera5@gmail.com"
        git config --local user.name "Himashana"
        git add --all
        git commit -m "Add changes" -a
      shell: bash
      
    - name: Push to GitHub repo
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
