name: Auto-build-plugin
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: zip the code
      run: |
        if [ -d "Auto-build-Plugin" ]; then
          rm -r Auto-build-Plugin
        fi
        
        mkdir Auto-build-Plugin
        cp -r src Auto-build-Plugin
        cd Auto-build-Plugin
        mv src maintenance-alerts
        zip -r maintenance-alerts.zip .
        pwd
        
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "himashanasuraweera5@gmail.com"
        git config --local user.name "Himashana"
        git add --all
        git commit -m "Auto-build"
# git commit -m "Add changes"
      shell: bash
      
    - name: Push to GitHub repo
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}

  Deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v1
    - name: Test path
      run: |
        pwd
        ls
        git status
