name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'maintenance-alerts.zip'
        path: '/bin/trunk'
        directory: '/bin'
        exclusions: '*.git* /*node_modules/* .editorconfig'
